myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

# from rest_framework import routers
from apps.recursos_humanos import views
from django.conf import settings
from django.conf.urls.static import static

# router = routers.DefaultRouter()
# router.register('empleados', views.EmpleadoViewSet)
# router.register('departamentos', views.DepartamentoViewSet)

urlpatterns = [
    path('', TemplateView.as_view(template_name='myproject/home.html')),
    path('campo_pruebas/', TemplateView.as_view(template_name='myproject/campo_pruebas.html')),
    path('recursos_humanos/', include('apps.recursos_humanos.urls')),
    path('admin/', admin.site.urls),
    # path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('apps.accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/recursos_humanos/models.py
from django.db import models


class Departamento(models.Model):
    nombre_departamento = models.CharField(
        max_length=200, help_text="Por favor escribe el Nombre del Departamento")
    descripcion_departamento = models.TextField()
    activo = models.BooleanField(
        default=True, verbose_name="Departamento Activo")
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Fecha de edición")

    def __str__(self):
        return self.nombre_departamento




class Empleado(models.Model):
    nombre = models.CharField(
        max_length=200, help_text="Escribe tu nombre de Pila")
    apellido = models.CharField(
        max_length=200, help_text="Escribe unicamente tu primer apellido")
    nacimiento = models.DateField()
    salario_mensual = models.DecimalField(
        max_digits=10, decimal_places=2, help_text="Escribe el Salario Mensual")
    direccion = models.CharField(max_length=200, verbose_name="Direccion")
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True, verbose_name="Usuario Activo")
    esc_primaria = 'Primaria'
    esc_secundaria = 'Secundaria'
    esc_preparatoria = 'Preparatoria'
    esc_licenciatura = 'Licenciatura Terminada'
    esc_licenciatura_trunca = 'Licenciatura Trunca'
    esc_opciones = (
        (esc_primaria, 'Primaria'),
        (esc_secundaria, 'Secundaria'),
        (esc_preparatoria, 'Preparatoria'),
        (esc_licenciatura, 'Licenciatura Trunca',),
        (esc_licenciatura_trunca, 'Licenciatura terminada'),
    )
    escolaridad = models.CharField(
        max_length=40,
        choices=esc_opciones,
    )
    imagen_perfil = models.ImageField(upload_to='images/', default='images/default.jpeg')
# De Momento no esta funcionando subir imagenes directamente desde el formulario, por eso siempre sube la imagen default




    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Fecha de edición")

    def __str__(self):
        return 'id: %s. %s, %s' % (self.id, self.nombre, self.apellido, )
        # return '%s %s. En Departamento:  %s' % (self.nombre, self.nacimiento, self.departamento)

templates/myproject/base.html
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Sistema de Administracion{% endblock %}</title>

    <link rel="shortcut icon" type="image/png " href="{% static 'favicon.ico' %}">

    <!-- Bootstrap y Jquery -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="http://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>

    <!-- Select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    <!-- Datatables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8"
        src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

    <!-- Datepicker -->
    <link rel="stylesheet" href="{% static 'css/jquery.datetimepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    {% block head %}
        
    {% endblock head%}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Admin</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                    <a class="nav-link" href="/">Inicio <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown {% if request.path == '/recursos_humanos/' %}active{% endif %}">
                    <a class="nav-link dropdown-toggle" href="{% url 'recursos_humanos' %}" id="navbarDropdown"
                        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Recursos Humanos
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'recursos_humanos_empleados' %}">Empleados</a>
                        <a class="dropdown-item" href="{% url 'recursos_humanos_departamentos' %}">Departamentos</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'recursos_humanos' %}">Ir a Recursos Humanos</a>
                    </div>
                </li>
                <li class="nav-item {% if request.path == '/campo_pruebas/' %}active{% endif %}">
                    <a class="nav-link" href="/campo_pruebas/">Campo de Pruebas <span
                            class="sr-only">(current)</span></a>
                </li>
            </ul>

            {% if user.is_authenticated %}
            {% comment %}
            Usuario Actual: {{ user.username }}
            {% endcomment %}

            <a class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'logout' %}">Cerrar Sesion</a>
            {% else %}
            <a class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'login' %}">Iniciar Sesion</a>
            <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'signup' %}">Registrarse</a>
            {% endif %}

        </div>
    </nav>


    <div class="container" style="margin-top: 1%; margin-bottom: 1%">
        {% block content %}
        {% endblock %}
    </div>

    {% comment %}
    <script src="{% static 'js/datepicker.js' %}"></script>
    <script src="{% static 'js/datatables.js' %}"></script>
    <script src="{% static 'js/select2.js' %}"></script>
    {% endcomment %}
    


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>

</html>

templates/myproject/campo_pruebas.html
{% extends 'myproject/base.html' %}


<title>{% block title %}Campo de Pruebas{% endblock %}</title>

{% block content %}

<h3>Campo de Pruebas</h3>

<p>El proposito de esta pagina es Probar Modales</p>

<!-- Boton Modal -->
<button class="btn btn-primary" data-toggle="modal" data-target="#modal1">
    Lanzar Modal Registro Nuevo Empleado
</button>

<!-- Modal1 -->

<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Dar de Alta nuevo Empleado</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <input type="hidden" name="csrfmiddlewaretoken"
                            value="c3FWFyBP0vfzjUPAoVuJqm9ej1kPS6ZbxXn0vcKmpgh3pxrFXhBQSns8RHoWiBq0">
                        <p><label for="id_nombre">Nombre:</label> <input type="text" name="nombre" class="form-control"
                                placeholder="Nombre" maxlength="200" required id="id_nombre"></p>
                        <p><label for="id_apellido">Apellido:</label> <input type="text" name="apellido"
                                class="form-control" placeholder="Apellido" maxlength="200" required id="id_apellido">
                        </p>
                        <p><label for="id_salario_mensual">Salario mensual:</label> <input type="text"
                                name="salario_mensual" class="form-control" placeholder="Salario Mensual" required
                                id="id_salario_mensual"></p>
                        <p><label for="id_direccion">Direccion:</label> <input type="text" name="direccion"
                                class="form-control" placeholder="Direccion" maxlength="200" required id="id_direccion">
                        </p>
                        <p><label for="id_departamento">Departamento:</label> <select name="departamento"
                                class="form-control" required id="id_departamento">
                                <option value="" selected>---------</option>

                                <option value="1">Desarrollo Web</option>

                                <option value="2">Contabilidad</option>

                                <option value="6">Finanzas</option>

                            </select></p>
                        <p><label for="id_escolaridad">Escolaridad:</label> <select name="escolaridad"
                                class="form-control" required id="id_escolaridad">
                                <option value="" selected>---------</option>

                                <option value="Primaria">Primaria</option>

                                <option value="Secundaria">Secundaria</option>

                                <option value="Preparatoria">Preparatoria</option>

                                <option value="Licenciatura Terminada">Licenciatura Trunca</option>

                                <option value="Licenciatura Trunca">Licenciatura terminada</option>

                            </select></p>
                        <p><label for="id_nacimiento">Nacimiento:</label> <input type="text" name="nacimiento"
                                class="form-control" autocomplete="off" required id="id_nacimiento"></p>
                        <p><label for="id_imagen_perfil">Imagen perfil:</label> <input type="file" name="imagen_perfil"
                                accept="image/*" id="id_imagen_perfil"></p>
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- Boton Modal2 -->
<button class="btn btn-primary" data-toggle="modal" data-target="#modal2">
    Lanzar Modal: Registrar nuevo Departamento
</button>

<!-- Modal1 -->
<div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Registrar nuevo departamento</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <input type="hidden" name="csrfmiddlewaretoken"
                            value="ndZBflhR1Il3JWOeQPLIsiUdy7RAbgupI7HF5ZqoqtnxPzqjpbSPUjd76NVHBLVe">
                        <p><label for="id_nombre_departamento">Nombre departamento:</label> <input type="text"
                                name="nombre_departamento" class="form-control" placeholder="Ejemplo: Contabilidad"
                                maxlength="200" required id="id_nombre_departamento"></p>
                        <p><label for="id_descripcion_departamento">Descripcion departamento:</label> <textarea
                                name="descripcion_departamento" cols="40" rows="4" class="form-control" required
                                id="id_descripcion_departamento">
                      </textarea></p>
                        <p><label for="id_activo">Departamento Activo:</label> <input type="checkbox" name="activo"
                                id="id_activo" checked></p>
                        <button type="submit" class="btn btn-success">Guardar</button>
                    </div>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/myproject/home.html
{% extends 'myproject/base.html' %}


<title>{% block title %}Sistema de Administracion{% endblock %}</title>

{% block content %}

        <h1>Lorem Ipsum</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempor hendrerit neque ut pretium. Maecenas
            elementum mauris nec lacus tincidunt pharetra. Sed sodales augue nec purus suscipit posuere. Sed tristique
            nisl ac posuere eleifend. Aliquam tincidunt ipsum a augue sollicitudin, non placerat augue porta. Vestibulum
            viverra sodales odio, mattis tempor mi. Morbi ut tristique sem. Etiam volutpat dignissim bibendum. Cras
            cursus viverra massa, vitae convallis ex condimentum ac. Vestibulum efficitur metus vitae porta sagittis.
        </p>

        <img src="https://via.placeholder.com/1110x768?text=Imagen+home+Prueba" class="img-fluid"
            alt="Esta Imagen Hace referencia a un Grupo de Empleados">

{% endblock %}

templates/myproject/signup.html
{% extends 'myproject/base.html' %}

{% block title %}Registrarse{% endblock %}

{% block content %}
<h2>Registrarse</h2>


{% if form.errors %}
<div class="alert alert-danger" role="alert">
    El usuario o la contrasena no cumple con los requisitos
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<form method="post">
    <div class="form-group">
        {% csrf_token %}
        <tr>
            <th><label for="id_username">Nombre de usuario:</label></th>
            <td><input type="text" name="username" maxlength="150" autofocus required id="id_username" class="form-control"><br><span
                    class="helptext" >Obligatorio. Longitud máxima 150 caracteres alfanuméricos. Letras, dígitos y
                    @/./+/-/_
                    únicamente.</span></td>
        </tr>
        <tr>
            <th><label for="id_password1">Contraseña:</label></th>
            <td><input type="password" name="password1" required id="id_password1" class="form-control"><br><span class="helptext">
                    <ul>
                        <li>Su contraseña no puede ser similar a su otra información personal.</li>
                        <li>Su contraseña es muy corta. Debe contener al menos 8 caracteres.</li>
                        <li>Su contraseña no puede ser una contraseña común.</li>
                        <li>Su contraseña no puede ser enteramente numérica.</li>
                    </ul>
                </span></td>
        </tr>
        <tr>
            <th><label for="id_password2">Confirmación de contraseña:</label></th>
            <td><input type="password" name="password2" required id="id_password2" class="form-control"><br><span class="helptext">Para
                    verificar, introduzca la misma contraseña que introdujo antes.</span></td>
        </tr>
        <button type="submit" class="btn btn-success">Guardar</button>
    </div>
</form>
{% endblock %}





{% comment %}
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Sign up</button>
</form>
{% endcomment %}